<?php	
	session_start();
	$code_length=5;
	$image_args=[
	'width'=>80,
	'height'=>20];
	$str="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
	$dot_num=100;
	for($i=0;$i<$code_length;$i++)
	{
		$code.=$str[rand(0,20)];
	}
	$_SESSION['yzm_code'] = $code;
	$image=imagecreate($image_args['width'],$image_args['height']);
	$background=imagecolorallocate($image,200,200,200);
	$text=imagecolorallocate($image, 0,0,0);
	$dot=imagecolorallocate($image,0,0,0);
	for($i=0;$i<$dot_num;$i++)
	{
		imagesetpixel($image,
			rand(0,$image_args['width']),
			rand(0,$image_args['height']),
			$dot);
	}
	imagestring($image,5,10,3,$code,$text);
	ob_clean();
	header('Cache-Control:private,max-age=0,no-store,no-cache,must-revalidate');
	header('Cache-Control:post-check=0,pre-check=0',false);
	header('Pragma:no-cache');
	header("content-type:image/png");
	imagepng($image);
	imagedestroy($image);
?>